### ISSUE TITLE
Getting no module found  error while running the node_webapp

### ISSUE THREAD

**Issue by kunjesh1** [kriscfoster/multi-language-bazel-monorepo#14]
<img width="991" alt="Screenshot 2022-09-06 at 2 39 26 PM" src="https://user-images.githubusercontent.com/16972191/188595574-ef9d96b1-a430-4b6d-9381-b3238ae1a47d.png">

```
Error: Cannot find module 'node_calculator'. Please verify that the package.json has a valid "main" entry
    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_kunjeshkumar/cf4baa9fa7a9487c4f93b13ff75cacf2/execroot/multi_language_monorepo/bazel-out/darwin-fastbuild/bin/projects/node_web/node_web_require_patch.cjs:528:17)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/kunjeshkumar/kk/tuts/multi-language-bazel-monorepo/projects/node_web/index.js:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Object.<anonymous> (/private/var/tmp/_bazel_kunjeshkumar/cf4baa9fa7a9487c4f93b13ff75cacf2/execroot/multi_language_monorepo/bazel-out/darwin-fastbuild/bin/projects/node_web/node_web_loader.cjs:34:24)```

**Comment by kriscfoster** [comment]
Hi @kunjesh1, what command are you running to get that error?
