### ISSUE TITLE
Unable to update npm dependencies

### ISSUE THREAD

**Issue by zpiazza-combocurve** [kriscfoster/multi-language-bazel-monorepo#32]
Hello,

I found this repo a while ago but was unable to get any of the projects to build successfully. I came back here seeing if there were any updates and was excited to see efforts to keep this repository maintained. When trying to install the npm dependencies, I am greeted with the following exception:

```
PS C:\Users\ZacharyPiazza\code\multi-language-bazel-monorepo> bazel run -- @pnpm//:pnpm i --dir C:\Users\ZacharyPiazza\code\multi-language-bazel-monorepo                  
ERROR: C:/users/zacharypiazza/_bazel_zacharypiazza/cozzzw7s/external/pnpm/BUILD.bazel:23:10: in js_binary rule @pnpm//:pnpm:                                                                                    
Traceback (most recent call last):
        File "C:/users/zacharypiazza/_bazel_zacharypiazza/cozzzw7s/external/aspect_rules_js/js/private/js_binary.bzl", line 553, column 32, in _impl
                launcher = _create_launcher(
        File "C:/users/zacharypiazza/_bazel_zacharypiazza/cozzzw7s/external/aspect_rules_js/js/private/js_binary.bzl", line 504, column 13, in _create_launcher
                fail("need --enable_runfiles on Windows for to support rules_js")
```

I tried the same on my Ubuntu WSL instance and got a completely different error:

```
zjpiazza@ZPSDTX00:/mnt/c/Users/ZacharyPiazza/code/multi-language-bazel-monorepo$ bazel run -- @pnpm//:pnpm i --dir $PWD --explain
Starting local Bazel server and connecting to it...
ERROR: /home/zjpiazza/.cache/bazel/_bazel_zjpiazza/c0716bbecca7bd32cd471befdc1a2b4a/external/rules_python/python/pip_install/pip_repository.bzl:234:29: name 'json' is not defined
ERROR: /home/zjpiazza/.cache/bazel/_bazel_zjpiazza/c0716bbecca7bd32cd471befdc1a2b4a/external/rules_python/python/pip_install/pip_repository.bzl:236:33: name 'json' is not defined
ERROR: /home/zjpiazza/.cache/bazel/_bazel_zjpiazza/c0716bbecca7bd32cd471befdc1a2b4a/external/rules_python/python/pip_install/pip_repository.bzl:556:12: name 'json' is not defined
ERROR: error loading package '': in /home/zjpiazza/.cache/bazel/_bazel_zjpiazza/c0716bbecca7bd32cd471befdc1a2b4a/external/rules_python/python/pip.bzl: Extension 'python/pip_install/pip_repository.bzl' has errors   
INFO: Elapsed time: 1.957s                                                                                                                                                                                            
INFO: 0 processes.                                                                                                                                                                                                    
FAILED: Build did NOT complete successfully (0 packages loaded)                                                                                                                                                       
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by zpiazza-combocurve** [comment]
Adding these options to the .bazelrc file seemed to do the trick for me:
```
build --enable_runfiles
startup --windows_enable_symlinks
```

**Comment by kriscfoster** [comment]
Thank you @zpiazza-combocurve, I've only really used this on macos & have never tried building it on windows/linux. Glad you got it working!
